name: thumper
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba
  - pandas>=1.2
  - python>=3.8
  - snakemake=6.5.0
  - pytest
  - git+https://github.com/dib-lab/sourmash@latest
