name: thumper-env
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - mamba
    - pytest
    - pandas>=1.03
    - python>=3.8
    - snakemake-minimal=5.21
    - pip:
      - pytest_dependency
