output_dir: output.thumper
#experiment_suffix: ""
logs_dir: logs
#sigs_dir: "sigs" #default: sigs_dir is under out_dir. Optionally enable user to specify a sigs dir?

pipeline: taxonomic_classification_gtdb


### default settings 
input_type: protein
alphabet: protein

gather_scaled: 1000

# defaults for each alphabet 
alphabet_defaults:
  nucleotide: 
    ksizes: [21,31,51]
    scaled: 1000
  protein:
    ksizes: [11]
    scaled: 100
  dayhoff:
    ksizes: [19]
    scaled: 100
  hp:
    ksizes: [33, 42]
    scaled: 100

## program params ##
sourmash_sketch_nucleotide:
  output_dir: signatures
  output_files:
    - "{sample}.nucleotide.sig"
  params:
    scaled: [100]
    # ksize --> don't set here. instead, get this from alpha defaults + user input!?

sourmash_sketch_protein:
  output_dir: signatures
  output_files:
    - "{sample}.protein.sig"
  params:
    # hmm. better to set universal defaults for all downstream steps.
    # --> don't set here. instead, get this from alpha defaults + user input!?
    scaled: [100]
    ksize: [11]

sourmash_gather_protein:
  output_dir: gather
  output_files:
    - "{sample}.x.{database}.gather-matches.csv"
    - "{sample}.x.{database}.gather-matches.sig"
    - "{sample}.x.{database}.gather-matches.txt"
    - "{sample}.x.{database}.gather-unassigned.sig"
  databases:
   - gtdb.rep_genus
  #params:
    #gather_scaled: 1000
    #extra: ""

sourmash_search_containment_protein:
  output_dir: search-containment
  output_files:
    - "{sample}.x.{database}.search-contain-matches.csv"
    - "{sample}.x.{database}.search-contain-matches.sig"
    - "{sample}.x.{database}.search-contain-matches.txt"
  databases:
   - gtdb.rep_genus

sourmash_gather_nucleotide:
  output_dir: gather
  output_files:
    - "{sample}.x.{database}.gather-matches.csv"
    - "{sample}.x.{database}.gather-matches.sig"
    - "{sample}.x.{database}.gather-matches.txt"
    - "{sample}.x.{database}.gather-unassigned.sig"
  databases:
   - gtdb.rep_genus
  #params:
    #gather_scaled: 1000
    #extra: ""

sourmash_search_containment_nucleotide:
  output_dir: search-containment
  output_files:
    - "{sample}.x.{database}.search-contain-matches.csv"
    - "{sample}.x.{database}.search-contain-matches.sig"
    - "{sample}.x.{database}.search-contain-matches.txt"
  databases:
   - gtdb.rep_genus

thumper_classify:
  output_dir: classify
  output_files:
    - "{basename}.x.{database}.classified.csv"
  params:
    threshold: .5 # potentially: the threshold for a gather tophit to be used for classification?
    tophit: True
    lca: True
    #extra: ""
