output_dir: output.thumper
basename: thumper
#experiment_suffix: ""
logs_dir: logs
#sigs_dir: "sigs" #default: sigs_dir is under out_dir. Optionally enable user to specify a sigs dir?

#pipeline: gtdb_classification_mag

### default settings 
default_input_type: protein

#protein_scaled: 10
#nucleotide_scaled: 1000
search_threshold: 0.001

# minimum fraction of hashes that must be identified to classify a genome
min_f_ident: 0.01

# minimum fraction of hashes that must be classified as lineage to -> genome
min_f_major: 0.01

# defaults for each alphabet 
alphabet_defaults:
  nucleotide: 
    ksizes: [21,31,51]
    scaled: 1000
    alpha_cmd: "--dna"
    moltype: "dna"
    ksize_multiplier: 1
  protein:
    ksizes: [11]
    scaled: 100
    alpha_cmd: "--protein"
    moltype: "protein"
    ksize_multiplier: 3
  dayhoff:
    ksizes: [19]
    scaled: 100
    alpha_cmd: "--dayhoff"
    moltype: "dayhoff"
    ksize_multiplier: 3
  hp:
    ksizes: [33]
    scaled: 100
    alpha_cmd: "--hp"
    moltype: "hp"
    ksize_multiplier: 3

## database info ##
default_database_info: .config/databases.csv
database_dir: databases
database_suffix: sbt.zip
database_info_suffix: info.csv
default_databases:
  - gtdb95-genus-n0 

## rule params ##
#sourmash_sketch:
#  output_dir: signatures
#  output_files:
#    - "{sample}.sig"

#sourmash_search_containment:
#  output_dir: search
#  output_files:
#    - "{sample}.x.{database}.matches.csv"
#    - "{sample}.x.{database}.matches.sig"
#    - "{sample}.x.{database}.matches.txt"

#contigs_search:
#  output_dir: contig-search
#  output_files:
#    - "{sample}.x.{database}.contigs.search.csv"
#    - "{sample}.x.{database}.contigs.ranksearch.csv"
#    - "{sample}.x.{database}.contigs.search.matches.sig"
#    - "{sample}.x.{database}.contigs.ranksearch.matches.sig"
#    - "{sample}.x.{database}.contigs.unmatched.fq"

#genome_search:
#  output_dir: genome-search
#  output_files:
#    - "{sample}.x.{database}.search.csv"
#    - "{sample}.x.{database}.ranksearch.csv"
#    - "{sample}.x.{database}.search.matches.sig"
#    - "{sample}.x.{database}.ranksearch.matches.sig"
#    - "{basename}.x.{database}.rankgather.csv"

#genome_report:
# make notebook, make_html
#    output_dir: reports
#    output_files:
#      - "{sample}.fig.ipynb"
#      - "{sample}.fig.html"

#summary_report:
#    output_dir: reports
#    output_files:
#      - "{basename}.x.{database}.index.ipynb"
#      - "{basename}.x.{database}.index.html"

#thumper_classify:
#   output_dir: classify
#   output_files:
#     - "{basename}.x.{database}.taxonomy-report.csv"
    #- "{basename}.x.{database}.classified.csv" --> final classification summary

## index snakefile ##
#signames_to_file:
#  output_dir: index
#  output_files:
#    - "{basename}.signatures.txt"

#index_sbt:
#  output_dir: index
#  output_files:
#    - "{index}.sbt.zip" # "index name" needs to include alphabet, ksize, scaled

## not currently in use ##
#sourmash_gather:
#  output_dir: gather
#  output_files:
#    - "{sample}.x.{database}.gather-matches.csv"
#    - "{sample}.x.{database}.gather-matches.sig"
#    - "{sample}.x.{database}.gather-matches.txt"
#    - "{sample}.x.{database}.gather-unassigned.sig"
#  databases:
#   - gtdb.rep_genus
#
