output_dir: output.thumper
basename: thumper
#experiment_suffix: ""
logs_dir: logs
#sigs_dir: "sigs" #default: sigs_dir is under out_dir. Optionally enable user to specify a sigs dir?

#pipeline: gtdb_classification_mag

### default settings 
default_input_type: protein

#protein_scaled: 10
#nucleotide_scaled: 1000
search_threshold: 0.001

# minimum fraction of hashes that must be identified to classify a genome
min_f_ident: 0.01

# minimum fraction of hashes that must be classified as lineage to -> genome
min_f_major: 0.01

# defaults for each alphabet 
alphabet_defaults:
  nucleotide: 
    ksizes: [21,31,51]
    scaled: [1000]
    alpha_cmd: "--dna"
    moltype: "dna"
    ksize_multiplier: 1
  protein:
    ksizes: [11]
    scaled: [100]
    alpha_cmd: "--protein"
    moltype: "protein"
    ksize_multiplier: 3
  dayhoff:
    ksizes: [19]
    scaled: [100]
    alpha_cmd: "--dayhoff"
    moltype: "dayhoff"
    ksize_multiplier: 3
  hp:
    ksizes: [33]
    scaled: [100]
    alpha_cmd: "--hp"
    moltype: "hp"
    ksize_multiplier: 3

## database info ##
default_database_info: .config/databases.csv
database_dir: databases
database_suffix: sbt.zip
database_info_suffix: info.csv
default_databases:
  - gtdb95-genus-n0 
