## use this to set workflows with default steps and databases
## maybe split nucl and protein into separate pipelines and/or snakefiles

pipelines:
  taxonomic_classification_gtdb:
    databases_required: True
    steps:
      nucleotide:
        - sourmash_sketch
        - sourmash_search_containment
        - contigs_taxonomy
        - make_hit_list
      protein:
        - sourmash_sketch
        - sourmash_search_containment
        - contigs_taxonomy
        - make_hit_list
        #- contig_classify
    databases:
      - gtdb.rep_genus
      #- gtdb-r89
  #taxonomic_classification_genbank:
  #protein_annotation_PFAM:
  generate_protein_index:
    databases_required: False
    steps:
      protein:
        - sourmash_sketch_protein
        - protein_signames_to_file
  generate_nucleotide_index:
    databases_required: False
    steps:
      nucleotide:
        - sourmash_sketch_nucleotide
        - nucleotide_signames_to_file
    
