## use this to set workflows with default steps and databases
## maybe split nucl and protein into separate pipelines and/or snakefiles

pipelines:
  taxonomic_classification_gtdb:
    databases_required: True
    steps:
      - sourmash_sketch
      - sourmash_search_containment
      - contigs_search
     # - make_hit_list
        #- contig_classify
    databases:
      - gtdb.rep_genus
      #- gtdb-r89
  #taxonomic_classification_genbank:
  #protein_annotation_PFAM:
  generate_index:
    databases_required: False
    steps:
      - sourmash_sketch
      - signames_to_file
      - index_sbt
