## use this to set workflows with default steps and databases
## maybe split nucl and protein into separate pipelines and/or snakefiles

pipelines:
  gtdb_classification_mag:
    databases_required: True
    steps:
      - sourmash_sketch
      - sourmash_search_containment
      - genome_search
    databases:
      - gtdb-genus-n0
      #- gtdb-r89
  gtdb_classification_contig:
    databases_required: True
    steps:
      - sourmash_sketch
      - sourmash_search_containment
      - genome_search # for now, just run both
      - contigs_search
      - genome_report
      - thumper_classify
      - summary_report
    databases:
      - gtdb-genus-n0
      #- gtdb-r89
  #taxonomic_classification_genbank:
  #protein_annotation_PFAM:
  generate_index:
    databases_required: False
    steps:
      - sourmash_sketch
      - signames_to_file
      - index_sbt
