## use this to set workflows with default steps and databases
## maybe split nucl and protein into separate pipelines and/or snakefiles

pipelines:
  taxonomic_classification_gtdb:
    steps:
      nucleotide:
        - sourmash_sketch_nucleotide
        #- sourmash_gather_nucleotide
        #- sourmash_search_containment_nucleotide
      protein:
        - sourmash_sketch_protein
        #- sourmash_gather_protein
        - sourmash_search_containment_protein
        - contig_classify
    databases:
      - gtdb.rep_genus
      #- gtdb-r89
  #taxonomic_classification_genbank:
  #protein_annotation_PFAM:
